### ISSUE TITLE
example in readme? or a console?

### ISSUE THREAD

**Issue by ignatandrei** [Otaman/Copycat#1]
I do maintain a list of Roslyn Code Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG 

I wish to add yours, but I need some use cases. Could you add into  the readme file?

**Comment by Otaman** [comment]
Hi @ignatandrei, thank you for your interest in the project. I've added some basic documentation and use-cases to explore. 

Please feel free to ask any further questions. It seems you are the first potential user of this package, so any comments or feedback would be very welcome.

**Comment by ignatandrei** [comment]
Thanks! see next issue ;-)

**Comment by ignatandrei** [comment]
https://ignatandrei.github.io/RSCG_Examples/v2/docs/CopyCat
